version: '3.8'

services:
  frontend:
    image: japipe05/androdri-frontend:v1.0.0
    container_name: androdri-frontend
    restart: always
    ports:
      - "3000:3000" # puerto público:puerto contenedor
    depends_on:
      - backend
    networks:
      - app-network
    env_file:
      - .env

  backend:
    image: japipe05/androdri-backend:v1.0.0
    container_name: androdri-backend
    restart: always
    ports:
      - "8000:8000" # puerto público:puerto contenedor (ajusta si usas otro)
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge
