version: "3.8"

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Panel de Traefik (opcional)
    networks:
      - androdri-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  backend:
    build:
      context: ./Backend
    container_name: androdri-backend
    ports:
      - "8000:8000"
    environment:
      FRONTEND_ORIGIN: "https://androdri.com"
      SMTP_HOST: "smtp.gmail.com"
      SMTP_PORT: "587"
      SMTP_USER: "felipehuchija@gmail.com"
      SMTP_PASSWORD: "yhjmdvmcvqidtxep"
      RECEIVER_EMAIL: "felipehuchija@gmail.com"
    networks:
      - androdri-network

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_CONTACT_API_URL: https://androdri.com/api/contact
    container_name: androdri-frontend
    networks:
      - androdri-network
    environment:
      - NEXT_PUBLIC_CONTACT_API_URL=https://androdri.com/api/contact
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`https://androdri.com`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

networks:
  androdri-network:
    driver: bridge
